/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multi.project.app;

import multi.project.utilities.Utils;

public class App {
    public static void main(String[] args) {
        System.out.println(Utils.isAllPositiveNumbers("12", "79"));;
    }
}
